'use client';
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";

type Campaign={id:string;created_at:string;title:string;facebook_post?:string;content:string;status:string};
type Customer={id:string;created_at:string;name:string;phone:string;email:string;preferred_contact:string;address:string;notes:string;status:string};
type Enquiry={id:string;created_at:string;status:string;source:string;customer_name:string;phone:string;email:string;preferred_contact:string;pickup_suburb:string;delivery_suburb:string;preferred_date:string;property_size:string;stairs:string;steep_driveway:string;heavy_items:string;item_summary:string;extra_notes:string;ai_summary:string;follow_up_at?:string;customer_id?:string};
type View="dashboard"|"enquiries"|"customers"|"receptionist"|"marketing"|"facebook"|"settings";

export default function Dashboard(){
 const router=useRouter();
 const [view,setView]=useState<View>("dashboard");
 const [userId,setUserId]=useState("");
 const [campaigns,setCampaigns]=useState<Campaign[]>([]);
 const [customers,setCustomers]=useState<Customer[]>([]);
 const [enquiries,setEnquiries]=useState<Enquiry[]>([]);
 const [selected,setSelected]=useState<Enquiry|null>(null);
 const [message,setMessage]=useState("");
 const [metaPosts,setMetaPosts]=useState<any[]>([]);
 const [metaConnected,setMetaConnected]=useState(false);
 const [metaLoading,setMetaLoading]=useState(false);
 const [lastSync,setLastSync]=useState("");
 const [customerForm,setCustomerForm]=useState({name:"",phone:"",email:"",preferred_contact:"phone",address:"",notes:""});
 const [search,setSearch]=useState("");

 useEffect(()=>{(async()=>{const {data}=await supabase.auth.getSession();if(!data.session){router.replace('/login');return}setUserId(data.session.user.id);await Promise.all([loadCampaigns(),loadCustomers(),loadEnquiries(),syncFacebook()]);})();},[]);
 async function loadCampaigns(){const {data}=await supabase.from('campaigns').select('*').order('created_at',{ascending:false});setCampaigns(data||[])}
 async function loadCustomers(){const {data}=await supabase.from('customers').select('*').order('created_at',{ascending:false});setCustomers(data||[])}
 async function loadEnquiries(){const {data}=await supabase.from('enquiries').select('*').order('created_at',{ascending:false});setEnquiries(data||[])}
 async function syncFacebook(){setMetaLoading(true);const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token){setMetaLoading(false);return}const r=await fetch('/api/meta',{headers:{Authorization:`Bearer ${token}`}});const j=await r.json();setMetaLoading(false);setLastSync(j.syncedAt||new Date().toISOString());if(r.ok){setMetaConnected(Boolean(j.connected));setMetaPosts(j.posts||[])}}
 async function setEnquiryStatus(id:string,status:string){const {error}=await supabase.from('enquiries').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error){setMessage(error.message);return}await loadEnquiries();if(selected?.id===id)setSelected({...selected,status});}
 async function setFollowUp(id:string,value:string){const follow_up_at=value?new Date(value).toISOString():null;const {error}=await supabase.from('enquiries').update({follow_up_at}).eq('id',id);if(error){setMessage(error.message);return}await loadEnquiries();}
 async function convertToCustomer(e:Enquiry){
   const {data,error}=await supabase.from('customers').insert({user_id:userId,name:e.customer_name,phone:e.phone,email:e.email||'',preferred_contact:e.preferred_contact||'phone',address:'',notes:e.ai_summary||e.extra_notes||'',status:'active'}).select('*').single();
   if(error){setMessage(error.message);return}
   await supabase.from('enquiries').update({customer_id:data.id,converted_at:new Date().toISOString(),status:e.status==='new'?'contacted':e.status}).eq('id',e.id);
   setMessage(`${e.customer_name} added to Customers.`);await Promise.all([loadCustomers(),loadEnquiries()]);setSelected(null);
 }
 async function addCustomer(){if(!customerForm.name||!customerForm.phone){setMessage('Customer name and phone are required.');return}const {error}=await supabase.from('customers').insert({user_id:userId,...customerForm,status:'active'});if(error){setMessage(error.message);return}setCustomerForm({name:'',phone:'',email:'',preferred_contact:'phone',address:'',notes:''});setMessage('Customer saved.');await loadCustomers();}
 async function deleteCustomer(id:string){if(!confirm('Delete this customer?'))return;await supabase.from('customers').delete().eq('id',id);await loadCustomers()}
 async function signOut(){await supabase.auth.signOut();router.replace('/login')}
 const newLeads=enquiries.filter(e=>e.status==='new').length;
 const followUps=enquiries.filter(e=>e.follow_up_at&&new Date(e.follow_up_at)<=new Date(Date.now()+86400000)&&!['closed','declined','booked'].includes(e.status)).length;
 const filteredCustomers=useMemo(()=>customers.filter(c=>(c.name+' '+c.phone+' '+c.email).toLowerCase().includes(search.toLowerCase())),[customers,search]);
 const filteredEnquiries=useMemo(()=>enquiries.filter(e=>(e.customer_name+' '+e.pickup_suburb+' '+e.delivery_suburb+' '+e.status).toLowerCase().includes(search.toLowerCase())),[enquiries,search]);

 return <div className="shell">
  <aside className="sidebar"><h2 className="brand">MHH AI Manager</h2><div className="tagline">FROM OUR HANDS TO YOUR HOME</div><div className="nav">{([['dashboard','Dashboard'],['enquiries','Enquiries'],['customers','Customers'],['receptionist','AI Receptionist'],['marketing','Marketing'],['facebook','Facebook'],['settings','Settings']] as [View,string][]).map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>{setView(id);setMessage('')}}>{label}</button>)}</div><div className="muted" style={{marginTop:24,fontSize:12}}>Version 4.0.0</div></aside>
  <main className="main"><div className="top"><div><h1>MHH AI Business Manager</h1><div className="muted">CRM · enquiry pipeline · website receptionist · marketing memory</div></div><div className="pill">{newLeads} new enquiries</div></div>
  {message&&<div className="notice">{message}</div>}

  <section className={view==='dashboard'?'view active':'view'}>
   <div className="grid"><div className="card"><div className="muted">New enquiries</div><div className="metric">{newLeads}</div></div><div className="card"><div className="muted">Customers</div><div className="metric">{customers.length}</div></div><div className="card"><div className="muted">Follow-ups due</div><div className="metric">{followUps}</div></div></div>
   <div className="grid two" style={{marginTop:18}}><div className="card"><h3>Needs attention</h3>{enquiries.filter(e=>e.status==='new').slice(0,5).map(e=><button className="leadRow" key={e.id} onClick={()=>{setSelected(e);setView('enquiries')}}><strong>{e.customer_name}</strong><span>{e.pickup_suburb} → {e.delivery_suburb}</span><span>{new Date(e.created_at).toLocaleDateString('en-AU')}</span></button>)}{!newLeads&&<p className="muted">No new enquiries.</p>}</div><div className="card"><h3>Business snapshot</h3><p>Website receptionist: <strong className="success">Live</strong></p><p>Facebook connection: <strong className={metaConnected?'success':'error'}>{metaConnected?'Connected':'Not connected'}</strong></p><p>Saved campaigns: <strong>{campaigns.length}</strong></p><div className="actions"><button className="btn" onClick={()=>setView('enquiries')}>Review enquiries</button><a className="btn secondary linkBtn" href="/reception" target="_blank">Open customer form</a></div></div></div>
  </section>

  <section className={view==='enquiries'?'view active':'view'}><div className="grid two"><div className="card"><div className="sectionHead"><h3>Enquiry Pipeline</h3><input className="searchBox" placeholder="Search enquiries" value={search} onChange={e=>setSearch(e.target.value)}/></div>{filteredEnquiries.map(e=><button key={e.id} className={`leadRow ${selected?.id===e.id?'selected':''}`} onClick={()=>setSelected(e)}><div><strong>{e.customer_name}</strong><span className="badge">{e.status}</span></div><span>{e.pickup_suburb} → {e.delivery_suburb}</span><span>{new Date(e.created_at).toLocaleString('en-AU')}</span></button>)}{!filteredEnquiries.length&&<p className="muted">No enquiries found.</p>}</div><div className="card">{!selected?<p className="muted">Select an enquiry to review it.</p>:<div><div className="sectionHead"><h3>{selected.customer_name}</h3><span className="badge">{selected.status}</span></div><p><strong>Phone:</strong> <a href={`tel:${selected.phone}`}>{selected.phone}</a></p><p><strong>Email:</strong> {selected.email||'Not supplied'}</p><p><strong>Preferred contact:</strong> {selected.preferred_contact}</p><div className="notice"><strong>Enquiry summary</strong><br/>{selected.ai_summary}</div><p><strong>Move:</strong> {selected.pickup_suburb} → {selected.delivery_suburb}</p><p><strong>Date:</strong> {selected.preferred_date||'Flexible / not supplied'}</p><p><strong>Property:</strong> {selected.property_size||'Not supplied'}</p><p><strong>Stairs:</strong> {selected.stairs} · <strong>Steep driveway:</strong> {selected.steep_driveway}</p><p><strong>Heavy items:</strong> {selected.heavy_items||'None listed'}</p><p><strong>Items:</strong> {selected.item_summary||'Not supplied'}</p><label>Status</label><select value={selected.status} onChange={e=>setEnquiryStatus(selected.id,e.target.value)}><option>new</option><option>contacted</option><option>quoted</option><option>booked</option><option>closed</option><option>declined</option></select><label>Follow-up date and time</label><input type="datetime-local" defaultValue={selected.follow_up_at?new Date(selected.follow_up_at).toISOString().slice(0,16):''} onBlur={e=>setFollowUp(selected.id,e.target.value)}/><div className="actions"><a className="btn linkBtn" href={`tel:${selected.phone}`}>Call customer</a><a className="btn secondary linkBtn" href={`sms:${selected.phone}`}>Send SMS</a>{!selected.customer_id&&<button className="btn secondary" onClick={()=>convertToCustomer(selected)}>Convert to customer</button>}</div></div>}</div></div></section>

  <section className={view==='customers'?'view active':'view'}><div className="grid two"><div className="card"><h3>Add Customer</h3><label>Name *</label><input value={customerForm.name} onChange={e=>setCustomerForm({...customerForm,name:e.target.value})}/><label>Phone *</label><input value={customerForm.phone} onChange={e=>setCustomerForm({...customerForm,phone:e.target.value})}/><label>Email</label><input value={customerForm.email} onChange={e=>setCustomerForm({...customerForm,email:e.target.value})}/><label>Preferred contact</label><select value={customerForm.preferred_contact} onChange={e=>setCustomerForm({...customerForm,preferred_contact:e.target.value})}><option value="phone">Phone</option><option value="sms">SMS</option><option value="email">Email</option><option value="facebook">Facebook</option></select><label>Address</label><input value={customerForm.address} onChange={e=>setCustomerForm({...customerForm,address:e.target.value})}/><label>Notes</label><textarea value={customerForm.notes} onChange={e=>setCustomerForm({...customerForm,notes:e.target.value})}/><button className="btn" onClick={addCustomer}>Save customer</button></div><div className="card"><div className="sectionHead"><h3>Customer Database</h3><input className="searchBox" placeholder="Search customers" value={search} onChange={e=>setSearch(e.target.value)}/></div>{filteredCustomers.map(c=><div className="campaign" key={c.id}><div className="sectionHead"><div><strong>{c.name}</strong><div className="muted">{c.phone} · {c.email||'No email'}</div></div><button className="btn danger" onClick={()=>deleteCustomer(c.id)}>Delete</button></div><p>{c.address}</p><p>{c.notes}</p><div className="actions"><a className="btn secondary linkBtn" href={`tel:${c.phone}`}>Call</a><a className="btn secondary linkBtn" href={`sms:${c.phone}`}>SMS</a></div></div>)}{!filteredCustomers.length&&<p className="muted">No customers found.</p>}</div></div></section>

  <section className={view==='receptionist'?'view active':'view'}><div className="grid two"><div className="card"><h3>Website Receptionist</h3><p>The new guided assistant collects the details needed for a removal quote and adds each request directly to the Enquiry Pipeline.</p><div className="notice">Required information: customer name, phone, pickup suburb and delivery suburb.</div><a className="btn linkBtn" href="/reception" target="_blank">Open public receptionist</a></div><div className="card"><h3>Add it to your website</h3><p>Use this route as the quote button destination:</p><div className="result">/reception</div><p className="muted">After deployment, the full address will be your Vercel domain followed by /reception.</p><p>New submissions appear under <strong>Enquiries</strong> with status <strong>new</strong>.</p></div></div></section>

  <section className={view==='marketing'?'view active':'view'}><div className="card"><h3>Marketing Module</h3><p>Your existing campaign records remain available. The full v3 campaign creator is preserved in the database and APIs.</p><p>Saved campaigns: <strong>{campaigns.length}</strong></p>{campaigns.slice(0,8).map(c=><div className="campaign" key={c.id}><strong>{c.title}</strong><span className="badge" style={{marginLeft:10}}>{c.status}</span><div className="result" style={{marginTop:10}}>{c.facebook_post||c.content}</div></div>)}</div></section>

  <section className={view==='facebook'?'view active':'view'}><div className="grid two"><div className="card"><h3>Facebook Connection</h3><p>Read access: <strong className={metaConnected?'success':'error'}>{metaConnected?'Connected':'Not connected'}</strong></p><p>Last sync: {lastSync?new Date(lastSync).toLocaleString('en-AU'):'Never'}</p><button className="btn" disabled={metaLoading} onClick={syncFacebook}>{metaLoading?'Syncing…':'Refresh Facebook Posts'}</button></div><div className="card"><h3>Recent Page Posts</h3>{metaPosts.map((p:any)=><div className="campaign" key={p.id}><div className="muted">{new Date(p.created_time).toLocaleString('en-AU')}</div><p>{p.message||'(Post without text)'}</p></div>)}</div></div></section>

  <section className={view==='settings'?'view active':'view'}><div className="card"><h3>System</h3><p>Application version: <strong>4.0.0</strong></p><p>Supabase authentication: <strong className="success">Connected</strong></p><p>CRM tables: <strong className="success">customers + enquiries</strong></p><p>Public receptionist route: <strong>/reception</strong></p><div className="notice">Run supabase/v4-migration.sql before using the CRM and receptionist.</div><button className="btn danger" onClick={signOut}>Sign out</button></div></section>
  </main>
 </div>
}
