 'use client';
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";

type Campaign={id:string;created_at:string;title:string;objective:string;audience:string;offer:string;content:string;facebook_post?:string;headline?:string;image_brief?:string;duplicate_warning?:string;status:string;meta_post_id?:string;published_at?:string};
type Draft={campaign_name:string;objective:string;audience:string;facebook_post:string;headline:string;description:string;call_to_action:string;image_brief:string;posting_time:string;paid_budget:string;website_support:string;measurement_plan:string;duplicate_warning:string;compliance_check:any};
type View="dashboard"|"create"|"campaigns"|"facebook"|"calendar"|"settings";

export default function Dashboard(){
 const router=useRouter(); const [view,setView]=useState<View>("dashboard"); const [userId,setUserId]=useState(""); const [campaigns,setCampaigns]=useState<Campaign[]>([]);
 const [objective,setObjective]=useState("Generate furniture-removal quote enquiries"); const [audience,setAudience]=useState("Adults in Nanango, Kingaroy and the South Burnett"); const [offer,setOffer]=useState("Reliable local furniture removals handled with care"); const [notes,setNotes]=useState("");
 const [draft,setDraft]=useState<Draft|null>(null); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(""); const [contextCount,setContextCount]=useState({posts:0,campaigns:0});
 const [metaConnected,setMetaConnected]=useState(false); const [metaPublishing,setMetaPublishing]=useState(false); const [metaMessage,setMetaMessage]=useState("Not checked"); const [metaPosts,setMetaPosts]=useState<any[]>([]); const [metaLoading,setMetaLoading]=useState(false); const [lastSync,setLastSync]=useState<string>("");

 useEffect(()=>{(async()=>{const {data}=await supabase.auth.getSession();if(!data.session){router.replace("/login");return}setUserId(data.session.user.id);await loadCampaigns();await syncFacebook();})();},[]);
 async function loadCampaigns(){const {data,error}=await supabase.from("campaigns").select("*").order("created_at",{ascending:false});if(!error)setCampaigns(data||[]);}
 async function generate(){setLoading(true);setMessage("");setDraft(null);const {data}=await supabase.auth.getSession();const token=data.session?.access_token;const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({objective,audience,offer,notes})});const j=await r.json();setLoading(false);if(!r.ok){setMessage(j.error||"Generation failed");return}setDraft(j.campaign);setContextCount({posts:j.recentPostsUsed||0,campaigns:j.savedCampaignsUsed||0});}
 async function save(){if(!draft)return;const content=[`Campaign name: ${draft.campaign_name}`,`Objective: ${draft.objective}`,`Audience: ${draft.audience}`,`Description: ${draft.description}`,`CTA: ${draft.call_to_action}`,`Posting time: ${draft.posting_time}`,`Paid budget: ${draft.paid_budget}`,`Website support: ${draft.website_support}`,`Measurement: ${draft.measurement_plan}`].join("\n");const {error}=await supabase.from("campaigns").insert({user_id:userId,title:draft.campaign_name,objective:draft.objective,audience:draft.audience,offer,content,facebook_post:draft.facebook_post,headline:draft.headline,image_brief:draft.image_brief,duplicate_warning:draft.duplicate_warning,status:"draft"});if(error){setMessage(error.message);return}setMessage("Campaign saved permanently.");await loadCampaigns();}
 async function updateStatus(id:string,status:string){await supabase.from("campaigns").update({status}).eq("id",id);await loadCampaigns();}
 async function remove(id:string){if(!confirm("Delete this campaign?"))return;await supabase.from("campaigns").delete().eq("id",id);await loadCampaigns();}
 async function syncFacebook(){setMetaLoading(true);setMetaMessage("Syncing Facebook…");const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token){setMetaLoading(false);return}const r=await fetch("/api/meta",{headers:{Authorization:`Bearer ${token}`}});const j=await r.json();setMetaLoading(false);setLastSync(j.syncedAt||new Date().toISOString());if(!r.ok){setMetaConnected(false);setMetaMessage(j.error||"Connection failed");return}setMetaConnected(Boolean(j.connected));setMetaPublishing(Boolean(j.publishingEnabled));setMetaMessage(j.connected?"Facebook posts synced successfully.":(j.message||"Not connected"));setMetaPosts(j.posts||[]);}
 async function publishCampaign(id:string){if(!confirm("Publish the approved Facebook caption now?"))return;const {data}=await supabase.auth.getSession();const token=data.session?.access_token;const r=await fetch("/api/meta/publish",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({campaignId:id})});const j=await r.json();if(!r.ok){alert(j.error||"Publishing failed");return}alert(j.message||"Published");await loadCampaigns();await syncFacebook();}
 async function signOut(){await supabase.auth.signOut();router.replace("/login");}
 const approved=campaigns.filter(c=>c.status==="approved").length; const published=campaigns.filter(c=>c.status==="published").length;
 return <div className="shell"><aside className="sidebar"><h2 className="brand">MHH AI Manager</h2><div className="tagline">FROM OUR HANDS TO YOUR HOME</div><div className="nav">{([["dashboard","Dashboard"],["create","Create Campaign"],["campaigns","Campaign Library"],["facebook","Facebook"],["calendar","Content Plan"],["settings","Settings"]] as [View,string][]).map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{label}</button>)}</div><div className="muted" style={{marginTop:24,fontSize:12}}>Version 3.0.0</div></aside>
 <main className="main"><div className="top"><div><h1>Marketing Manager v3</h1><div className="muted">Facebook sync · campaign memory · approval workflow</div></div><div className="pill">{metaPublishing?"Publishing enabled":"Publishing disabled"}</div></div>
 <section className={view==="dashboard"?"view active":"view"}><div className="grid"><div className="card"><div className="muted">Saved campaigns</div><div className="metric">{campaigns.length}</div></div><div className="card"><div className="muted">Approved drafts</div><div className="metric">{approved}</div></div><div className="card"><div className="muted">Published posts</div><div className="metric">{published}</div></div></div><div className="card" style={{marginTop:18}}><h3>Facebook status</h3><p className={metaConnected?"success":"error"}>{metaMessage}</p><p>Recent posts loaded: <strong>{metaPosts.length}</strong></p><p>Last sync: <strong>{lastSync?new Date(lastSync).toLocaleString("en-AU"):"Not synced"}</strong></p><div className="actions"><button className="btn" onClick={()=>setView("create")}>Create campaign</button><button className="btn secondary" onClick={syncFacebook}>Sync Facebook</button></div></div></section>
 <section className={view==="create"?"view active":"view"}><div className="grid two"><div className="card"><h3>Campaign Brief</h3><label>Objective</label><select value={objective} onChange={e=>setObjective(e.target.value)}><option>Generate furniture-removal quote enquiries</option><option>Generate phone calls</option><option>Increase local Facebook engagement</option><option>Promote Marketplace pickups</option><option>Promote small house moves</option></select><label>Audience</label><input value={audience} onChange={e=>setAudience(e.target.value)}/><label>Offer or message</label><input value={offer} onChange={e=>setOffer(e.target.value)}/><label>Extra instructions</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Example: Friday evening engagement post."/><div className="actions"><button className="btn" onClick={generate} disabled={loading}>{loading?"Checking history & generating…":"Generate draft"}</button><button className="btn secondary" onClick={save} disabled={!draft}>Save campaign</button></div>{message&&<p className={message.includes("saved")?"success":"error"}>{message}</p>}</div><div className="card"><h3>Facebook Campaign Draft</h3>{!draft?<div className="result muted">Your Facebook-aware campaign will appear here.</div>:<div><span className="badge">{contextCount.posts} Page posts + {contextCount.campaigns} saved campaigns checked</span><h3>{draft.headline}</h3><div className="notice"><strong>Exact Facebook caption</strong></div><div className="result">{draft.facebook_post}</div><p><strong>Recommended time:</strong> {draft.posting_time}</p><p><strong>Image brief:</strong> {draft.image_brief}</p><p><strong>Duplicate check:</strong> {draft.duplicate_warning}</p><p><strong>Website support:</strong> {draft.website_support}</p></div>}</div></div></section>
 <section className={view==="campaigns"?"view active":"view"}><div className="card"><h3>Campaign Library</h3>{campaigns.length===0?<p className="muted">No campaigns saved yet.</p>:campaigns.map(c=><div className="campaign" key={c.id}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><strong>{c.title}</strong><div className="muted">{new Date(c.created_at).toLocaleString("en-AU")}</div></div><span className="badge">{c.status}</span></div>{c.duplicate_warning&&<div className="notice"><strong>Duplicate check:</strong> {c.duplicate_warning}</div>}<details style={{marginTop:12}}><summary>View Facebook caption</summary><div className="result" style={{marginTop:12}}>{c.facebook_post||c.content}</div></details>{c.image_brief&&<details style={{marginTop:12}}><summary>View image brief</summary><p>{c.image_brief}</p></details>}<div className="actions">{c.status!=="published"&&<button className="btn secondary" onClick={()=>updateStatus(c.id,"approved")}>Approve</button>}{c.status!=="published"&&<button className="btn secondary" onClick={()=>updateStatus(c.id,"draft")}>Return to draft</button>}{c.status==="approved"&&metaPublishing&&<button className="btn" onClick={()=>publishCampaign(c.id)}>Publish approved caption</button>}<button className="btn danger" onClick={()=>remove(c.id)}>Delete</button></div></div>)}</div></section>
 <section className={view==="facebook"?"view active":"view"}><div className="grid two"><div className="card"><h3>Facebook Business Page</h3><p>The dashboard automatically syncs recent posts when you sign in.</p><div className="actions"><button className="btn" onClick={syncFacebook} disabled={metaLoading}>{metaLoading?"Syncing…":"Refresh Facebook Posts"}</button></div><p className={metaConnected?"success":"error"}>{metaMessage}</p><p>Read access: <strong>{metaConnected?"Connected":"Not connected"}</strong></p><p>Publishing: <strong>{metaPublishing?"Enabled":"Disabled"}</strong></p><p>Last synced: <strong>{lastSync?new Date(lastSync).toLocaleString("en-AU"):"Never"}</strong></p></div><div className="card"><h3>Recent Page Posts</h3>{!metaPosts.length?<p className="muted">No recent posts loaded.</p>:metaPosts.map((p:any)=><div className="campaign" key={p.id}><div className="muted">{new Date(p.created_time).toLocaleString("en-AU")}</div><p>{p.message||"(Post without text)"}</p>{p.permalink_url&&<a href={p.permalink_url} target="_blank" rel="noreferrer" style={{color:"var(--gold2)"}}>Open on Facebook</a>}</div>)}</div></div></section>
 <section className={view==="calendar"?"view active":"view"}><div className="card"><h3>Recommended Weekly Content Plan</h3><p><strong>Monday:</strong> Marketplace pickup engagement post</p><p><strong>Wednesday:</strong> Removal quote lead-generation post</p><p><strong>Friday:</strong> Weekend availability or moving tip</p><div className="notice">Scheduling will be added after publishing is tested.</div></div></section>
 <section className={view==="settings"?"view active":"view"}><div className="card"><h3>Security & Connections</h3><p>Supabase login: <strong className="success">Connected</strong></p><p>Facebook Page: <strong className={metaConnected?"success":"error"}>{metaConnected?"Connected":"Not connected"}</strong></p><p>Facebook-aware generation: <strong className={metaConnected?"success":"error"}>{metaConnected?"Active":"Inactive"}</strong></p><p>Application version: <strong>3.0.0</strong></p><div className="notice">Publishing remains controlled by META_PUBLISHING_ENABLED in Vercel.</div><button className="btn danger" onClick={signOut}>Sign out</button></div></section>
 </main></div>;
}
